version: '2'
services:
  tftpd:
    image: kalaksi/tftpd
    restart: unless-stopped
    environment:
      # Search the man page for --blocksize to learn more
      TFTPD_EXTRA_ARGS: '--blocksize 1468'
    cap_drop:
      - ALL
    cap_add:
      - SETUID
      - SETGID
      - SYS_CHROOT
    ports:
      - 69:1069/udp
    volumes:
      - tftpd_boot:/tftpboot/boot
      - tftpd_configuration:/tftpboot/pxelinux.cfg:ro

volumes:
  tftpd_boot: {}
  tftpd_configuration: {}

